### ISSUE TITLE
Couchbase

### ISSUE THREAD

**Issue by ghost** [flimzy/go-pouchdb#41]
Did you deep this with a Couchbase backend ?

Just want to check because there are many couch backendss these days.

Looks pretty cool though. Will be giving this a whirl

**Comment by ghost** [comment]
Also any example app ?

**Comment by flimzy** [comment]
I have not tested with Couchbase, but as it's just a wrapper around PouchDB, it should work.  Please submit any bug reports you find, though.

And I don't have any example apps. It might be something I can add later, if/when time permits.

**Comment by ghost** [comment]
thanks @flimzy for the response. Really appreciated.

Ok i will play around and see how i go, and raise issues etc.

Are you using this in real world app ? just so i know if its bug ridden or not :)

**Comment by flimzy** [comment]
I have been using it regularly in a development app... And there are tests covering a good portion of it. But there are likely a few small bugs on parts I haven't tested.

But I should be able to fix any discovered bugs pretty quickly, as it's just a thin wrapper around PouchDB.

**Comment by ghost** [comment]
ok got it. thanks.
will play around now...
