### ISSUE TITLE
Live replication

### ISSUE THREAD

**Issue by jackkleeman** [flimzy/go-pouchdb#44]
Can live two way (or one way) replication be achieved using go-pouchdb? Your readme mentions one-shot only. Is this for a particular reason? I suppose an easy workaround is to initiate replication from js code instead of from go.

**Comment by flimzy** [comment]
Live replication doesn't work yet because there's no way to handle the event feeds. Once #42 is resolved, I expect live replication to be easy.

**Comment by jackkleeman** [comment]
Great, thanks

**Comment by flimzy** [comment]
I'll leave this open, as a reminder to myself (and any future readers) that this is a WIP.

**Comment by flimzy** [comment]
I have begun work on a new library intended to make `go-pouchdb` obsolete. The primary feature is a unified CouchDB library for both Go and GopherJS, but one of the things I've done is used an iterator interface for both the changes feed, as well as standard view queries. It's still in development, but I welcome any feedback you may offer on the work as it stands, as making changes early is easier than making them late! :)

The project can be viewed on GitHub: https://github.com/flimzy/kivik
Or you can read the current Go Doc, specifically as it relates to the changes feed, here: https://godoc.org/github.com/flimzy/kivik#DB.ChangesContext

**Comment by jackkleeman** [comment]
Wow, this will be great for me and @JustinDrake.
BTW, I have been using your changes branch successfully in production code for a while without any problems.

**Comment by JustinDrake** [comment]
I don't get the significance of kivik for us @jackkleeman. Being stupid :)

**Comment by jackkleeman** [comment]
Well more pouchdb features would be useful if callable from gopherjs eg better changefeed manipulation and replication.

**Comment by flimzy** [comment]
As this is now fully supported by [Kivik](https://github.com/flimzy/kivik), which supersedes this package, I am going to close this issue.
