### ISSUE TITLE
$global.require is not a function

### ISSUE THREAD

**Issue by fiatjaf** [flimzy/go-pouchdb#50]
My `main.go` file:

```go
package main

import (
    "log"

    "github.com/flimzy/go-pouchdb"
)
    
func main() {
    db := pouchdb.New("test")
    log.Print(db)
}
```

I run `gopherjs build -mvw` and go to localhost:8080. I see a blank screen and the error on the console.

The `index.html` is the one automatically generated by `gopherjs serve`. I have installed pouchdb with `npm install pouchdb`.

**Comment by fiatjaf** [comment]
I see there are ongoing discussions about `require` at the gopherjs repository, but are there any solutions?

**Comment by flimzy** [comment]
Thank you for the report. I'm on vacation away from my computer for a few days, but will take a closer look when I can. In the meantime can you tell me what error you're getting?

**Comment by fiatjaf** [comment]
`$global.require is not a function`

That's the error.

I also tried applying browserify to the file  generated by `gopherjs`, but got the same.

Then I tried modifying the "prelude" it generates, so `$global. require = require` no matter what, then got a "maximum call stack reached" inside the browserify prelude.

**Comment by flimzy** [comment]
Using browserify should solve that problem. An alternative is just to load PouchDB normally in your HTML in a `script` tag.  I'm not sure how either of those options would be done in conjunction with GopherJS's serve command. You mentioned both `build` and `serve` in your original message. Can you include the full command(s) you're executing? 

Again, I'll dig in deeper when I'm at my PC.

**Comment by fiatjaf** [comment]
My plan was to use go-pouchdb as basis for another gopherjs library, which then would be exported to `module.exports` and would be able to be required by javascript apps as javascript people normally do.

I tried many different things, that's why I mentioned different commands, but basically all them fail if I try the browserify-style `require`. Did you actually managed to get it working?

Including pouchdb in a `<script>` tag works.

**Comment by flimzy** [comment]
I have not tried loading compiled GopherJS as a JS module, but I am regularly using `require` to load JS modules in GopherJS (both with Node.js and browserify). Tomorrow or Sunday I should be able to investigate further, and maybe provide additional documentation for you. Thanks for your patience.

**Comment by fiatjaf** [comment]
I've managed to load compiled gopherjs as a JS module. It's the other way around that is giving me trouble.

I've not tried with nodejs or webpack, only browserify. 

Thank you for your help, patience and additional documentation.

**Comment by flimzy** [comment]
I'm finally back at my computer today, and able to look at this.  I've merged a small change with #51 to make 'require' work better with browserify. Would you let me know how this works for you now, and if you have additional issues?

**Comment by fiatjaf** [comment]
It works! Thank you very much.

For future reference, I did `go get -u github.com/flimzy/go-pouchdb`, then created a `main.go` with

```go
package main

import (
    "github.com/flimzy/go-pouchdb"
    "honnef.co/go/js/console"
)

func main() {
    db := pouchdb.New("gopouchtest")
    rev, err := db.Put(map[string]string{"_id": "hello"})
    console.Log(rev, err)
    var f interface{}
    err = db.Get("hello", &f, pouchdb.Options{})
    console.Log(err, f)
    console.Log(db.Destroy(pouchdb.Options{}))
}
```

compiled it with `gopherjs build main.go`. This generated a `main.js`, which I passed to browserify: `browserify main.js -o bundle.js`, which I then served in an `index.html`:

```html
<!doctype html>
<script src=bundle.js></script>
```

**Comment by flimzy** [comment]
I'm glad it's working now! Again, I'm sorry for the delay in responding while I was on vacation. Thanks for the patience!
